# Generated by Django 4.1.1 on 2022-09-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.IntegerField(default=0)),
                ('ativo', models.BooleanField()),
                ('classificacao', models.CharField(max_length=255)),
            ],
        ),
    ]
